# This file was generated by GoReleaser. DO NOT EDIT.
class Pullreminders < Formula
  desc "GitHub pullreminders"
  homepage "https://github.com/g-gaston/pullreminders"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/g-gaston/pullreminders/releases/download/v0.0.1/pullreminders_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "c407436c06591111179df42d3d0565fc2e7f36c3e4345f15cb08b51b40087ba9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/g-gaston/pullreminders/releases/download/v0.0.1/pullreminders_0.0.1_Linux_x86_64.tar.gz"
      sha256 "dfc1d0e7497d0e955e65aa207fcef6a1764cf5cf1a098c92c51e3e37ea3f3651"
    end
  end
  
  head do
    url "https://github.com/g-gaston/pullreminders.git"
    depends_on "go"
  end

  def install
    bin.install "pullreminders"
  end
end
